### ISSUE TITLE
Skipped during loading

### ISSUE THREAD

**Issue by VolaNova** [Ser-Hilary/SDXL_sizing#2]
I installed this through the ComfyUI Manager and after restarting I get this message during startup:

Skip D:\AIComfy\ComfyUI\custom_nodes\conditioning_sizing_for_SDXL.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

I downloaded an older version of the script and it worked fine.

**Comment by Ser-Hilary** [comment]
oh, I'll add those lines back to the conditioning_sizing_for_SDXL.py file in case it gets installed that way.

when this is git cloned to a folder, ComfyUI will look for those in the __init__.py, so I removed them from the other since I assumed it wasn't doing anything for anyone.

**Comment by VolaNova** [comment]
Thanks! Works for me now!
