### ISSUE TITLE
target_width and target_height in sizing (basic) and sizing (advanced)

### ISSUE THREAD

**Issue by fractal-fumbler** [Ser-Hilary/SDXL_sizing#3]
hello :)
thanks a lot for your work!

noticed difference in placements of outputs in basic and advanced node 
![image](https://github.com/Ser-Hilary/SDXL_sizing/assets/80472908/19eeb10c-c9da-45ea-b5e3-fde625ede392)
![image](https://github.com/Ser-Hilary/SDXL_sizing/assets/80472908/14a98757-6def-4dc2-bc93-4daf2067177e)

so, basic gives:
```got prompt                                                                                                              
torch.Size([1, 1280]) 1600 1100 2 0 4928 3392                                                                           
torch.Size([1, 1280]) 1600 1100 2 0 4928 3392
```

and advanced gives:
```got prompt                                                                                                              
width: 1600                                                                                                             
height: 1100                                                                                                            
crop_w: 2                                                                                                               
crop_h: 0                                                                                                               
target_width: 4928                                                                                                      
target_height: 3392                                                                                                     
downscale: 1.0                                                                                                          
torch.Size([1, 1280]) 1600 1100 4928 3392 2 0                                                                        
torch.Size([1, 1280]) 1600 1100 4928 3392 2 0
```

what are correct placement of target_width and target_height?

**Comment by Ser-Hilary** [comment]
Was one in your workflow prior to an update? At one point I changed it to line up with the order of the inputs on the SDXL prompt node (admittedly, it should have been that way to begin with...)

 Since the basic node inherits the class from the advanced node they should have the same output order, but I know that nodes from old workflows will be broken because they display the old outputs (and, consequently, don't work.)
 
 edit: Oh and to answer your question the order should be,
 width
 height
 crop_w
 crop_h
 target_w
 target_h

**Comment by fractal-fumbler** [comment]
got it, thanks :)
yup, not was one in saved earlier workflow.

thanks a lot for your time!
